version: '3'

networks:
  traefik_web:
    external: true
    
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    networks:
      - traefik_web
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /data/app_data/portainer/data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=web, websecure"
      - "traefik.http.routers.portainer.rule=Host(`portainer.zuhause`)" #DNS Namen für App festlegen
      - "traefik.htpp.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=production" #Bei Test- und Probedurchläufen production durch staging ersetzen. Bei jedem Service!
      - "traefik.http.services.portainer.loadbalancer.server.port=9000" #Port der App wenn sie per Dafault mehr denn 2 hat 