version: "3"

networks:
  traefik_web:
    external: true

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      - traefik_web
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: '123'
    volumes:
      - '/data/app_data/pihole/etc-pihole:/etc/pihole'
      - '/data/app_data/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.entrypoints=web, websecure"
      - "traefik.http.routers.pihole.rule=Host(`pihole.zuhause`)" #DNS Namen für App festlegen
      - "traefik.htpp.routers.pihole.tls=false"
      - "traefik.http.routers.pihole.tls.certresolver=production" #Bei Test- und Probedurchläufen production durch staging ersetzen. Bei jedem Service!
      - "traefik.http.services.pihole.loadbalancer.server.port=8080" #Port der App wenn sie per Dafault mehr denn 2 hat 
    restart: always
